2022-11-11 17:18:02,585 INFO    MainThread:13772 [wandb_setup.py:_flush():68] Configure stats pid to 13772
2022-11-11 17:18:02,585 INFO    MainThread:13772 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Zabraf\.config\wandb\settings
2022-11-11 17:18:02,585 INFO    MainThread:13772 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Zabraf\Documents\Github\TB_DQN_A2C_CartePole\wandb\settings
2022-11-11 17:18:02,585 INFO    MainThread:13772 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'pytorchDQN.py', 'program': 'c:\\Users\\Zabraf\\Documents\\Github\\TB_DQN_A2C_CartePole\\pytorchDQN.py'}
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\Zabraf\Documents\Github\TB_DQN_A2C_CartePole\wandb\run-20221111_171802-1rpfwtfz\logs\debug.log
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\Zabraf\Documents\Github\TB_DQN_A2C_CartePole\wandb\run-20221111_171802-1rpfwtfz\logs\debug-internal.log
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:init():516] calling init triggers
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:init():569] starting backend
2022-11-11 17:18:02,586 INFO    MainThread:13772 [wandb_init.py:init():573] setting up manager
2022-11-11 17:18:02,589 INFO    MainThread:13772 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-11 17:18:02,592 INFO    MainThread:13772 [wandb_init.py:init():580] backend started and connected
2022-11-11 17:18:02,593 INFO    MainThread:13772 [wandb_init.py:init():658] updated telemetry
2022-11-11 17:18:02,712 INFO    MainThread:13772 [wandb_init.py:init():692] communicating run to backend with 30 second timeout
2022-11-11 17:18:05,739 WARNING MainThread:13772 [wandb_init.py:init():1097] interrupted
Traceback (most recent call last):
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1076, in init
    run = wi.init()
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 696, in init
    result = handle.wait(
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\mailbox.py", line 76, in wait
    found = self._slot._get_and_clear(timeout=1)
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\mailbox.py", line 35, in _get_and_clear
    if self._event.wait(timeout=timeout):
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\threading.py", line 600, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\Zabraf\AppData\Local\Programs\Python\Python310\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-11-11 17:18:05,758 WARNING MsgRouterThr:13772 [router.py:message_loop():77] message_loop has been closed
